version: '3'
services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        restart: always
        network_mode: bridge
        ports:
            - 80:80
        depends_on: 
            - db
        volumes:
            - ./src/:/var/www/html/vendor/blackoutzz/framework/src/
            - ./html/controllers/:/var/www/html/controllers/
            - ./html/ui/:/var/www/html/ui/
            - ./html/logs/apache/:/var/log/apache2/
            - ./config/php/:/usr/local/etc/php/
            - ./html/logs/sessions/:/tmp/php/sessions/
        environment: 
            - HASH_ALGO=SHA-512
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=admin
            - ADMIN_EMAIL=admin@localhost
    db:
        image: mariadb
        restart: always
        network_mode: bridge
        environment:
            MYSQL_ROOT_PASSWORD: zP*YM3W%!2tZoj9&8AheE3Ws
            MYSQL_USER: admin
            MYSQL_PASSWORD: 3XukYj&bnBHaP&38uuSjph@R
            MYSQL_DATABASE: app
