version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 80:80
        #volumes:
        #    - ./src/:/var/www/html/vendor/blackoutzz/framework/src/